# Generated by Django 4.2.1 on 2023-06-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando aprovação', 'Aguardando aprovação'), ('ativado', 'Ativado'), ('apagado', 'Apagado')], default='ativado', max_length=50),
        ),
    ]
