# Generated by Django 4.2.1 on 2023-07-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_email_userprofile_email_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Nif',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cep_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='endereco_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nif_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefone_empresa',
        ),
    ]
