# Generated by Django 4.2.1 on 2023-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_nif_userprofile_apelido_userprofile_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cep_empresa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_empresa',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='endereco_empresa',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nif_empresa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_empresa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone_empresa',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
